// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv0KQ-yJ_hNXaMJr-cwafwaUVreVx5V1A',
    appId: '1:422045634434:web:975ec2bc9db198a77c899b',
    messagingSenderId: '422045634434',
    projectId: 'fbase12-154a8',
    authDomain: 'fbase12-154a8.firebaseapp.com',
    storageBucket: 'fbase12-154a8.firebasestorage.app',
    measurementId: 'G-7LTJ4VFRZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhHCUn4utsn7PJ_tJgTvpfvTC7VZxHUt8',
    appId: '1:422045634434:android:d8401bb83d6b52647c899b',
    messagingSenderId: '422045634434',
    projectId: 'fbase12-154a8',
    storageBucket: 'fbase12-154a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-FcN9nNKVUnR6W6Qx8ke5KtgZNIZxoBg',
    appId: '1:422045634434:ios:7bcc5e5d56dc47d17c899b',
    messagingSenderId: '422045634434',
    projectId: 'fbase12-154a8',
    storageBucket: 'fbase12-154a8.firebasestorage.app',
    iosBundleId: 'com.example.fbase12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-FcN9nNKVUnR6W6Qx8ke5KtgZNIZxoBg',
    appId: '1:422045634434:ios:7bcc5e5d56dc47d17c899b',
    messagingSenderId: '422045634434',
    projectId: 'fbase12-154a8',
    storageBucket: 'fbase12-154a8.firebasestorage.app',
    iosBundleId: 'com.example.fbase12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv0KQ-yJ_hNXaMJr-cwafwaUVreVx5V1A',
    appId: '1:422045634434:web:b42be84163adf68b7c899b',
    messagingSenderId: '422045634434',
    projectId: 'fbase12-154a8',
    authDomain: 'fbase12-154a8.firebaseapp.com',
    storageBucket: 'fbase12-154a8.firebasestorage.app',
    measurementId: 'G-ZXQ4QNLYYP',
  );
}
